name: Check Code Convention
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Check Code Convention
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
      - name: pick_random_reviwer
        id: pick_random_reviwer
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const candidate = ['reviewer1', 'reviewer2', 'reviewer3'];
            const randomReviewer = candidate[Math.floor(Math.random() * candidate.length)];
            const comment = `🎉 @${randomReviewer} 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏`
            core.setOutput('comment', comment) 
            core.setOutput('reviewer', randomReviewer) // core.setOutput(이름, 값)

      - name: comment PR
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ steps.pick_random_reviwer.outputs.comment }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'

      - name: Add Pull Request Reviewer
        uses: madrapps/add-reviewers@v1
        with:
          reviewers: ${{ steps.pick_random_reviwer.outputs.reviewer }}
          token: ${{ secrets.GITHUB_TOKEN }}
